name: Release
on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write # may want to update version
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_SETTINGS_EXPERIM: ${{ vars.MAVEN_SETTINGS_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify
        run: |
          if [[ -n "$SONATYPE_USERNAME" ]]
          then
            echo "DEBUG have SONATYPE_USERNAME"
          else 
            echo "Release requires SONATYPE_USERNAME, which was not found. exiting"
            exit 1
          fi

          if [[ -n "$SONATYPE_PASSWORD" ]]
          then
            echo "have SONATYPE_PASSWORD"
          else 
            echo "Release requires SONATYPE_PASSWORD, which was not found. exiting"
            exit 1
          fi
          
          echo "DEBUG MAVEN_SETTINGS_EXPERIM ${MAVEN_SETTINGS_EXPERIM}"
          echo "DEBUG MAVEN_SETTINGS_FILE ${{ vars.MAVEN_SETTINGS_FILE }}"
          
          # N.B. this is for debugging only.  TODO remove before release
          mvn -s ${{ vars.MAVEN_SETTINGS_FILE }} help:effective-settings

          if ! command -v gpg2 &> /dev/null
          then
            echo "Failed to locate gpg2 on this host.  GPG2 is required to continue."
            exit 1
          fi
          
          gpg2 --version
