name: Release Experiments
on:
  release:
    types: [created]

jobs:
  release-exp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Verify
        run: |
          echo "Experimental releasing"
          echo "DEBUG GITHUB_SHA #${GITHUB_SHA}#"
          echo "DEBUG GITHUB_REF #${GITHUB_REF}#"
        
